In [0]:
import numpy as np
from sklearn import datasets
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
np.unique(iris_y)
len(iris_X)

150

In [4]:
indices = np.random.permutation(len(iris_X))
iris_X_train = iris_X[indices[:-10]]
iris_y_train = iris_y[indices[:-10]]
iris_X_test = iris_X[indices[-10:]]
iris_y_test = iris_y[indices[-10:]]
knn = KNeighborsClassifier()
knn.fit(iris_X_train, iris_y_train) 
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=5, p=2,
           weights='uniform')
knn.predict(iris_X_test)
print(iris_X_train)
print(iris_y_train)
print(iris_X_test)
iris_y_test

[[6.3 2.8 5.1 1.5]
 [6.2 2.8 4.8 1.8]
 [4.8 3.  1.4 0.3]
 [6.7 3.3 5.7 2.5]
 [5.7 2.8 4.5 1.3]
 [6.4 2.8 5.6 2.1]
 [4.8 3.  1.4 0.1]
 [4.6 3.2 1.4 0.2]
 [5.1 3.3 1.7 0.5]
 [6.4 3.2 5.3 2.3]
 [6.7 3.1 5.6 2.4]
 [5.  3.5 1.3 0.3]
 [4.9 3.1 1.5 0.1]
 [6.1 2.8 4.7 1.2]
 [7.7 2.6 6.9 2.3]
 [6.  3.  4.8 1.8]
 [4.8 3.1 1.6 0.2]
 [6.9 3.1 4.9 1.5]
 [6.8 3.  5.5 2.1]
 [5.8 2.7 3.9 1.2]
 [6.  2.2 5.  1.5]
 [7.7 3.8 6.7 2.2]
 [6.7 2.5 5.8 1.8]
 [6.1 3.  4.9 1.8]
 [5.4 3.9 1.7 0.4]
 [5.1 3.5 1.4 0.3]
 [6.7 3.1 4.7 1.5]
 [6.5 3.  5.2 2. ]
 [5.7 2.5 5.  2. ]
 [5.  3.2 1.2 0.2]
 [5.5 2.6 4.4 1.2]
 [6.3 2.5 5.  1.9]
 [5.5 2.4 3.7 1. ]
 [6.3 3.3 6.  2.5]
 [5.7 2.6 3.5 1. ]
 [6.5 3.  5.8 2.2]
 [4.7 3.2 1.3 0.2]
 [5.6 2.5 3.9 1.1]
 [5.5 2.4 3.8 1.1]
 [5.5 4.2 1.4 0.2]
 [6.2 2.2 4.5 1.5]
 [5.  3.4 1.6 0.4]
 [5.8 2.6 4.  1.2]
 [5.7 3.8 1.7 0.3]
 [7.  3.2 4.7 1.4]
 [6.5 3.2 5.1 2. ]
 [7.2 3.2 6.  1.8]
 [5.6 2.7 4.2 1.3]
 [6.5 3.  5.5 1.8]
 [5.  3.3 1.4 0.2]
 [6.8 2.8 4.8 1.4]
 [6.9 3.1 5.4 2.1]
 [6.4 2.9 4.

array([0, 0, 2, 1, 1, 0, 2, 1, 2, 0])